# Learning outcomes

1. check time usage for multiplying list of million numbers by 2 between numpy and normal list
2. create ndarrays (np.array, ndim, shape, dtype, zeros, ones, empty)
3. checking datatype, casting datatype (int, float, string)
4. do arithmetic with numpy arrays [+, - *, /, **, boolean(<, >, ==, <=, >=)]
5. do slicing and indexing on numpy arrays (2-d, 3-d arrays), explcitly copy arrays
6. indexing with slices

In [1]:
import numpy as np

## Introduction

In [8]:
# generate random numpy array of  shape (2,3)
# multiply by 10, addition
# check shape
# check data type

data = np.random.randn(2,3)
print(data * 10)
print(data + data)
print(data.shape, data.dtype)

[[  7.32613947  -3.25889746   8.66962338]
 [-15.31184347 -12.64345439  11.75299801]]
[[ 1.46522789 -0.65177949  1.73392468]
 [-3.06236869 -2.52869088  2.3505996 ]]
(2, 3) float64


## Creating ndarrays (n-dimensional arrays)

generally, creating ndarrays takes in the:
- no. of `rows`
- no. of `columns`
- no. of `"matrixes"` to create

In [9]:
# create ndarray from python list
data1 = [6, 7.5, 8 , 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [11]:
# create ndarray from nested list, numpy interprets the shape
data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)
arr2, arr2.shape

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 (2, 4))

In [14]:
# create array of zeroes
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [17]:
# create array of ones
np.ones(10), \
np.ones((10,3)) , \
np.ones((1,2,2))

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([[[1., 1.],
         [1., 1.]]]))

In [22]:
# create array of range using arange
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
# create empty ndarray
np.empty((10,2))

array([[9.48032341e-312, 6.27463370e-322],
       [0.00000000e+000, 0.00000000e+000],
       [7.56587583e-307, 5.30276956e+180],
       [6.74640243e-067, 4.57399874e-071],
       [4.46156275e-086, 3.35809400e-143],
       [6.01433264e+175, 6.93885958e+218],
       [5.56218858e+180, 3.94356143e+180],
       [1.54673988e-075, 2.21549880e-056],
       [1.25581128e-075, 8.30112254e-067],
       [5.50622817e-144, 1.50008929e+248]])

## Data types for ndarrays

In [35]:
# passing dtype as argument when creating ndarray
arr1 = np.array([1,2,3], dtype=np.float64)

In [37]:
# inferring dtype
arr2 = np.array([i for i in range(1,6)])
arr2.dtype

dtype('int32')

In [39]:
# casting dtypes using astype
arr2.astype(np.float64)

array([1., 2., 3., 4., 5.])

In [40]:
# casting dtypes using another arrays dtype
arr2.astype(arr1.dtype)

array([1., 2., 3., 4., 5.])

In [42]:
# converting to string type: becareful with this conversion due to truncation of values
arr2.astype(np.string_)

array([b'1', b'2', b'3', b'4', b'5'], dtype='|S11')

## Arithmetic with numpy arrays

ndarrays are useful because arithmetics can be done without for loops on each element

In [56]:
arr1 = np.array([[1,2,3], [4,5,6]], dtype=np.int64)
arr1

array([[1, 2, 3],
       [4, 5, 6]], dtype=int64)

In [45]:
arr1 - arr1

array([[0, 0, 0],
       [0, 0, 0]])

In [46]:
arr1 * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [49]:
1 / arr1

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [50]:
arr1 ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [60]:
arr2 = np.array([[1,3,3], [4,6,6]], dtype=np.float64)

In [62]:
# one thing to note here is the data type, int can be compared with float, numeric types cannot be compared with string types
arr1 == arr2

array([[ True, False,  True],
       [ True, False,  True]])

## Basic Indexing and slicing

In [67]:
arr = np.arange(10)
# indexing
arr[5]

# slicing
arr[5:8]

# assigning values propagates array
arr[5:8] = 42
arr

array([ 0,  1,  2,  3,  4, 42, 42, 42,  8,  9])

In [77]:
# numpy does not explicitly do a copy on its array
arr_slice = arr[5:8]

# assigning values mutates original array
arr_slice = 42
arr

In [78]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    42, 12345,    42,     8,
           9])

In [80]:
# slicing 2d arrays
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# easy to think of it as rows, columns
# first row, third column
arr2d[0, 2]
arr2d[0][2]

3

In [96]:
# slicing 3d arrays
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [90]:
# first "table", row 1
arr3d[0, 1]

array([4, 5, 6])

In [97]:
# getting a copy of original values from 3d array
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [100]:
# 2nd "table", 1st row
arr3d[1, 0]

array([7, 8, 9])

In [101]:
# creating a view of 3d array, 2nd "table"
x = arr3d[1]
x[0] # view of 2nd table of first row of 3d array

array([7, 8, 9])

## Indexing with slices

In [105]:
# slice 1d array to get elements indexing from 1 to 5
arr = np.arange(10)
arr[1:6]

array([1, 2, 3, 4, 5])

In [114]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [107]:
# slice 2d array to get up to 2nd row
arr2d
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
# slice 2d array to get up to 2nd row, and 2nd column onwards
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [110]:
# slice 2d array to get 2nd row, and up to 2nd column
arr2d[1, :2]

array([4, 5])

In [111]:
# slice 2d array to get up to 2nd row, and 3rd column
arr2d[:2, 2]

array([3, 6])

In [113]:
# get all rows, up to first column
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [116]:
# assign values to a sliced view of up to 2nd row, 2nd column onwards
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## Boolean Indexing

In [138]:
# using a 1-d boolean array to index a 2d array
# the 1-d boolean array shape should be the same as the shape of axis you are indexing
# for e.g. each element in below names 1-d array will represent a row in the 2-d data array
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7,4)

# using names == 'Bob', it gives only rows 1 (0), and 4 (3) 
data[names == 'Bob']

array([[-0.42463581, -0.18134816,  0.63041968,  0.21258265],
       [ 0.38212256, -0.83348734,  0.42088411, -0.54690572]])

In [121]:
data

array([[ 1.30573576, -0.88909004,  2.49942848,  0.05047768],
       [-1.22975819,  0.9658055 , -0.7517069 ,  1.97226735],
       [ 0.6990872 , -0.15195539,  0.44330737,  0.39206532],
       [ 0.11028854, -1.53991342, -0.89928461,  0.25383515],
       [ 0.23802579, -2.32678251,  1.06519825,  0.41867376],
       [ 0.40257791,  1.98849158, -0.89028077, -0.2962391 ],
       [ 0.33686579, -0.23039406,  0.77176592,  1.1677816 ]])

In [119]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [120]:
# boolean indexing rows, get from column 3 onwards
data[names == 'Bob', 2:]

array([[ 2.49942848,  0.05047768],
       [-0.89928461,  0.25383515]])

In [122]:
# boolean indexing rows, get column 4
data[names == 'Bob', 3]

array([0.05047768, 0.25383515])

In [123]:
# negate using !=, ~
print(names != 'Bob')
data[names != 'Bob']

[False  True  True False  True  True  True]


array([[-1.22975819,  0.9658055 , -0.7517069 ,  1.97226735],
       [ 0.6990872 , -0.15195539,  0.44330737,  0.39206532],
       [ 0.23802579, -2.32678251,  1.06519825,  0.41867376],
       [ 0.40257791,  1.98849158, -0.89028077, -0.2962391 ],
       [ 0.33686579, -0.23039406,  0.77176592,  1.1677816 ]])

In [125]:
data[~(names == 'Bob')]

array([[-1.22975819,  0.9658055 , -0.7517069 ,  1.97226735],
       [ 0.6990872 , -0.15195539,  0.44330737,  0.39206532],
       [ 0.23802579, -2.32678251,  1.06519825,  0.41867376],
       [ 0.40257791,  1.98849158, -0.89028077, -0.2962391 ],
       [ 0.33686579, -0.23039406,  0.77176592,  1.1677816 ]])

In [127]:
# creating a 'filter' using a variable
cond = names == 'Bob'
data[~cond]

array([[-1.22975819,  0.9658055 , -0.7517069 ,  1.97226735],
       [ 0.6990872 , -0.15195539,  0.44330737,  0.39206532],
       [ 0.23802579, -2.32678251,  1.06519825,  0.41867376],
       [ 0.40257791,  1.98849158, -0.89028077, -0.2962391 ],
       [ 0.33686579, -0.23039406,  0.77176592,  1.1677816 ]])

In [129]:
# and, or in filters
mask = (names == 'Bob') | (names == 'Will')
data[mask]

array([[ 1.30573576, -0.88909004,  2.49942848,  0.05047768],
       [ 0.6990872 , -0.15195539,  0.44330737,  0.39206532],
       [ 0.11028854, -1.53991342, -0.89928461,  0.25383515],
       [ 0.23802579, -2.32678251,  1.06519825,  0.41867376]])

In [132]:
# using 2-d arrays to boolean index 2-d arrays and assigning values
data[data < 0] = 0
data

array([[1.30573576, 0.        , 2.49942848, 0.05047768],
       [0.        , 0.9658055 , 0.        , 1.97226735],
       [0.6990872 , 0.        , 0.44330737, 0.39206532],
       [0.11028854, 0.        , 0.        , 0.25383515],
       [0.23802579, 0.        , 1.06519825, 0.41867376],
       [0.40257791, 1.98849158, 0.        , 0.        ],
       [0.33686579, 0.        , 0.77176592, 1.1677816 ]])

In [139]:
# using boolean 1-d array to boolean index 2-d arrays and assigning values
data[names != 'Joe'] = 7
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.30666845, -1.54223474, -0.12703713,  0.59766009],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.8266089 ,  0.07233187,  2.13627856,  2.21138349],
       [ 0.4419279 , -0.12498884,  0.57992766,  0.07536175]])