In [1]:
import numpy as np

## Introduction

In [8]:
# generate random numpy array of  shape (2,3)
# multiply by 10, addition
# check shape
# check data type

data = np.random.randn(2,3)
print(data * 10)
print(data + data)
print(data.shape, data.dtype)

[[  7.32613947  -3.25889746   8.66962338]
 [-15.31184347 -12.64345439  11.75299801]]
[[ 1.46522789 -0.65177949  1.73392468]
 [-3.06236869 -2.52869088  2.3505996 ]]
(2, 3) float64


## Creating ndarrays (n-dimensional arrays)

generally, creating ndarrays takes in the:
- no. of `rows`
- no. of `columns`
- no. of `"matrixes"` to create

In [9]:
# create ndarray from python list
data1 = [6, 7.5, 8 , 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [11]:
# create ndarray from nested list, numpy interprets the shape
data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)
arr2, arr2.shape

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 (2, 4))

In [14]:
# create array of zeroes
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [17]:
# create array of ones
np.ones(10), \
np.ones((10,3)) , \
np.ones((1,2,2))

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([[[1., 1.],
         [1., 1.]]]))

In [22]:
# create array of range using arange
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
# create empty ndarray
np.empty((10,2))

array([[9.48032341e-312, 6.27463370e-322],
       [0.00000000e+000, 0.00000000e+000],
       [7.56587583e-307, 5.30276956e+180],
       [6.74640243e-067, 4.57399874e-071],
       [4.46156275e-086, 3.35809400e-143],
       [6.01433264e+175, 6.93885958e+218],
       [5.56218858e+180, 3.94356143e+180],
       [1.54673988e-075, 2.21549880e-056],
       [1.25581128e-075, 8.30112254e-067],
       [5.50622817e-144, 1.50008929e+248]])

## Data types for ndarrays

In [35]:
# passing dtype as argument when creating ndarray
arr1 = np.array([1,2,3], dtype=np.float64)

In [37]:
# inferring dtype
arr2 = np.array([i for i in range(1,6)])
arr2.dtype

dtype('int32')

In [39]:
# casting dtypes using astype
arr2.astype(np.float64)

array([1., 2., 3., 4., 5.])

In [40]:
# casting dtypes using another arrays dtype
arr2.astype(arr1.dtype)

array([1., 2., 3., 4., 5.])

In [42]:
# converting to string type: becareful with this conversion due to truncation of values
arr2.astype(np.string_)

array([b'1', b'2', b'3', b'4', b'5'], dtype='|S11')

## Arithmetic with numpy arrays

ndarrays are useful because arithmetics can be done without for loops on each element

In [56]:
arr1 = np.array([[1,2,3], [4,5,6]], dtype=np.int64)
arr1

array([[1, 2, 3],
       [4, 5, 6]], dtype=int64)

In [45]:
arr1 - arr1

array([[0, 0, 0],
       [0, 0, 0]])

In [46]:
arr1 * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [49]:
1 / arr1

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [50]:
arr1 ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [55]:
arr2 = np.array([[1,3,3], [4,6,6]], dtype=np.float64)

In [57]:
# one thing to note here is the data type
arr1 == arr2

array([[ True, False,  True],
       [ True, False,  True]])